//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.3062.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
[System.Xml.Serialization.XmlRootAttribute("policyDefinitions", Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions", IsNullable=false)]
public partial class PolicyDefinitions {
    
    private PolicyNamespaces policyNamespacesField;
    
    private FileReference[] supersededAdmField;
    
    private Annotation[] annotationField;
    
    private LocalizationResourceReference resourcesField;
    
    private SupportedOnTable supportedOnField;
    
    private CategoryList categoriesField;
    
    private PolicyList policiesField;
    
    private string revisionField;
    
    private string schemaVersionField;
    
    /// <remarks/>
    public PolicyNamespaces policyNamespaces {
        get {
            return this.policyNamespacesField;
        }
        set {
            this.policyNamespacesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("supersededAdm")]
    public FileReference[] supersededAdm {
        get {
            return this.supersededAdmField;
        }
        set {
            this.supersededAdmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation")]
    public Annotation[] annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public LocalizationResourceReference resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    public SupportedOnTable supportedOn {
        get {
            return this.supportedOnField;
        }
        set {
            this.supportedOnField = value;
        }
    }
    
    /// <remarks/>
    public CategoryList categories {
        get {
            return this.categoriesField;
        }
        set {
            this.categoriesField = value;
        }
    }
    
    /// <remarks/>
    public PolicyList policies {
        get {
            return this.policiesField;
        }
        set {
            this.policiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class PolicyNamespaces {
    
    private PolicyNamespaceAssociation targetField;
    
    private PolicyNamespaceAssociation[] usingField;
    
    /// <remarks/>
    public PolicyNamespaceAssociation target {
        get {
            return this.targetField;
        }
        set {
            this.targetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("using")]
    public PolicyNamespaceAssociation[] @using {
        get {
            return this.usingField;
        }
        set {
            this.usingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class PolicyNamespaceAssociation {
    
    private string prefixField;
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string @namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ComboBox))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TextBox))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public abstract partial class DataElement {
    
    private string refIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refId {
        get {
            return this.refIdField;
        }
        set {
            this.refIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ComboBox : DataElement {
    
    private string labelField;
    
    private string defaultField;
    
    private string[] suggestionField;
    
    private bool noSortField;
    
    public ComboBox() {
        this.noSortField = false;
    }
    
    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("suggestion")]
    public string[] suggestion {
        get {
            return this.suggestionField;
        }
        set {
            this.suggestionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool noSort {
        get {
            return this.noSortField;
        }
        set {
            this.noSortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class TextBox : DataElement {
    
    private string labelField;
    
    private string defaultValueField;
    
    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public string defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ListBox))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DropdownList))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CheckBox))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DecimalTextBox))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public abstract partial class DataElementContent {
    
    private string refIdField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string refId {
        get {
            return this.refIdField;
        }
        set {
            this.refIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ListBox : DataElementContent {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class DropdownList : DataElementContent {
    
    private bool noSortField;
    
    private uint defaultItemField;
    
    private bool defaultItemFieldSpecified;
    
    public DropdownList() {
        this.noSortField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool noSort {
        get {
            return this.noSortField;
        }
        set {
            this.noSortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint defaultItem {
        get {
            return this.defaultItemField;
        }
        set {
            this.defaultItemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultItemSpecified {
        get {
            return this.defaultItemFieldSpecified;
        }
        set {
            this.defaultItemFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class CheckBox : DataElementContent {
    
    private bool defaultCheckedField;
    
    public CheckBox() {
        this.defaultCheckedField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool defaultChecked {
        get {
            return this.defaultCheckedField;
        }
        set {
            this.defaultCheckedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class DecimalTextBox : DataElementContent {
    
    private uint defaultValueField;
    
    private bool spinField;
    
    private uint spinStepField;
    
    public DecimalTextBox() {
        this.defaultValueField = ((uint)(1));
        this.spinField = true;
        this.spinStepField = ((uint)(1));
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "1")]
    public uint defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool spin {
        get {
            return this.spinField;
        }
        set {
            this.spinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "1")]
    public uint spinStep {
        get {
            return this.spinStepField;
        }
        set {
            this.spinStepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class PolicyPresentation {
    
    private object[] itemsField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("checkBox", typeof(CheckBox))]
    [System.Xml.Serialization.XmlElementAttribute("comboBox", typeof(ComboBox))]
    [System.Xml.Serialization.XmlElementAttribute("decimalTextBox", typeof(DecimalTextBox))]
    [System.Xml.Serialization.XmlElementAttribute("dropdownList", typeof(DropdownList))]
    [System.Xml.Serialization.XmlElementAttribute("listBox", typeof(ListBox))]
    [System.Xml.Serialization.XmlElementAttribute("text", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("textBox", typeof(TextBox))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class LocalizedString {
    
    private string idField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class Localization {
    
    private LocalizationStringTable stringTableField;
    
    private LocalizationPresentationTable presentationTableField;
    
    /// <remarks/>
    public LocalizationStringTable stringTable {
        get {
            return this.stringTableField;
        }
        set {
            this.stringTableField = value;
        }
    }
    
    /// <remarks/>
    public LocalizationPresentationTable presentationTable {
        get {
            return this.presentationTableField;
        }
        set {
            this.presentationTableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class LocalizationStringTable {
    
    private LocalizedString[] stringField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("string")]
    public LocalizedString[] @string {
        get {
            return this.stringField;
        }
        set {
            this.stringField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class LocalizationPresentationTable {
    
    private PolicyPresentation[] presentationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("presentation")]
    public PolicyPresentation[] presentation {
        get {
            return this.presentationField;
        }
        set {
            this.presentationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ListElement {
    
    private string idField;
    
    private string clientExtensionField;
    
    private string keyField;
    
    private string valuePrefixField;
    
    private bool additiveField;
    
    private bool expandableField;
    
    private bool explicitValueField;
    
    public ListElement() {
        this.additiveField = false;
        this.expandableField = false;
        this.explicitValueField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientExtension {
        get {
            return this.clientExtensionField;
        }
        set {
            this.clientExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valuePrefix {
        get {
            return this.valuePrefixField;
        }
        set {
            this.valuePrefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool additive {
        get {
            return this.additiveField;
        }
        set {
            this.additiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool expandable {
        get {
            return this.expandableField;
        }
        set {
            this.expandableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool explicitValue {
        get {
            return this.explicitValueField;
        }
        set {
            this.explicitValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class EnumerationElement {
    
    private EnumerationElementItem[] itemField;
    
    private string idField;
    
    private string clientExtensionField;
    
    private string keyField;
    
    private string valueNameField;
    
    private bool requiredField;
    
    public EnumerationElement() {
        this.requiredField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public EnumerationElementItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientExtension {
        get {
            return this.clientExtensionField;
        }
        set {
            this.clientExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class EnumerationElementItem {
    
    private Value valueField;
    
    private ValueList valueListField;
    
    private string displayNameField;
    
    /// <remarks/>
    public Value value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public ValueList valueList {
        get {
            return this.valueListField;
        }
        set {
            this.valueListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class Value {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("decimal", typeof(ValueDecimal))]
    [System.Xml.Serialization.XmlElementAttribute("delete", typeof(ValueDelete))]
    [System.Xml.Serialization.XmlElementAttribute("string", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ValueDecimal {
    
    private uint valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ValueDelete {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ValueList {
    
    private ValueItem[] itemField;
    
    private string defaultKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item")]
    public ValueItem[] item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultKey {
        get {
            return this.defaultKeyField;
        }
        set {
            this.defaultKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class ValueItem {
    
    private Value valueField;
    
    private string keyField;
    
    private string valueNameField;
    
    /// <remarks/>
    public Value value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class TextElement {
    
    private string idField;
    
    private string clientExtensionField;
    
    private string keyField;
    
    private string valueNameField;
    
    private bool requiredField;
    
    private uint maxLengthField;
    
    private bool expandableField;
    
    private bool softField;
    
    public TextElement() {
        this.requiredField = false;
        this.maxLengthField = ((uint)(1023));
        this.expandableField = false;
        this.softField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientExtension {
        get {
            return this.clientExtensionField;
        }
        set {
            this.clientExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "1023")]
    public uint maxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool expandable {
        get {
            return this.expandableField;
        }
        set {
            this.expandableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool soft {
        get {
            return this.softField;
        }
        set {
            this.softField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class DecimalElement {
    
    private string idField;
    
    private string clientExtensionField;
    
    private string keyField;
    
    private string valueNameField;
    
    private bool requiredField;
    
    private uint minValueField;
    
    private uint maxValueField;
    
    private bool storeAsTextField;
    
    private bool softField;
    
    public DecimalElement() {
        this.requiredField = false;
        this.minValueField = ((uint)(0));
        this.maxValueField = ((uint)(9999));
        this.storeAsTextField = false;
        this.softField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientExtension {
        get {
            return this.clientExtensionField;
        }
        set {
            this.clientExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
    public uint minValue {
        get {
            return this.minValueField;
        }
        set {
            this.minValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(typeof(uint), "9999")]
    public uint maxValue {
        get {
            return this.maxValueField;
        }
        set {
            this.maxValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool storeAsText {
        get {
            return this.storeAsTextField;
        }
        set {
            this.storeAsTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool soft {
        get {
            return this.softField;
        }
        set {
            this.softField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class BooleanElement {
    
    private Value trueValueField;
    
    private Value falseValueField;
    
    private ValueList trueListField;
    
    private ValueList falseListField;
    
    private string idField;
    
    private string clientExtensionField;
    
    private string keyField;
    
    private string valueNameField;
    
    /// <remarks/>
    public Value trueValue {
        get {
            return this.trueValueField;
        }
        set {
            this.trueValueField = value;
        }
    }
    
    /// <remarks/>
    public Value falseValue {
        get {
            return this.falseValueField;
        }
        set {
            this.falseValueField = value;
        }
    }
    
    /// <remarks/>
    public ValueList trueList {
        get {
            return this.trueListField;
        }
        set {
            this.trueListField = value;
        }
    }
    
    /// <remarks/>
    public ValueList falseList {
        get {
            return this.falseListField;
        }
        set {
            this.falseListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clientExtension {
        get {
            return this.clientExtensionField;
        }
        set {
            this.clientExtensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class PolicyDefinition {
    
    private Annotation[] annotationField;
    
    private CategoryReference parentCategoryField;
    
    private string[] seeAlsoField;
    
    private string keywordsField;
    
    private SupportedOnReference supportedOnField;
    
    private Value enabledValueField;
    
    private Value disabledValueField;
    
    private ValueList enabledListField;
    
    private ValueList disabledListField;
    
    private object[] elementsField;
    
    private string nameField;
    
    private PolicyClass classField;
    
    private string displayNameField;
    
    private string explainTextField;
    
    private string presentationField;
    
    private string keyField;
    
    private string valueNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation")]
    public Annotation[] annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public CategoryReference parentCategory {
        get {
            return this.parentCategoryField;
        }
        set {
            this.parentCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seeAlso")]
    public string[] seeAlso {
        get {
            return this.seeAlsoField;
        }
        set {
            this.seeAlsoField = value;
        }
    }
    
    /// <remarks/>
    public string keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    public SupportedOnReference supportedOn {
        get {
            return this.supportedOnField;
        }
        set {
            this.supportedOnField = value;
        }
    }
    
    /// <remarks/>
    public Value enabledValue {
        get {
            return this.enabledValueField;
        }
        set {
            this.enabledValueField = value;
        }
    }
    
    /// <remarks/>
    public Value disabledValue {
        get {
            return this.disabledValueField;
        }
        set {
            this.disabledValueField = value;
        }
    }
    
    /// <remarks/>
    public ValueList enabledList {
        get {
            return this.enabledListField;
        }
        set {
            this.enabledListField = value;
        }
    }
    
    /// <remarks/>
    public ValueList disabledList {
        get {
            return this.disabledListField;
        }
        set {
            this.disabledListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("boolean", typeof(BooleanElement), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("decimal", typeof(DecimalElement), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("enum", typeof(EnumerationElement), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("list", typeof(ListElement), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("text", typeof(TextElement), IsNullable=false)]
    public object[] elements {
        get {
            return this.elementsField;
        }
        set {
            this.elementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PolicyClass @class {
        get {
            return this.classField;
        }
        set {
            this.classField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string explainText {
        get {
            return this.explainTextField;
        }
        set {
            this.explainTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string presentation {
        get {
            return this.presentationField;
        }
        set {
            this.presentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueName {
        get {
            return this.valueNameField;
        }
        set {
            this.valueNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class Annotation {
    
    private System.Xml.XmlNode[] anyField;
    
    private string applicationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class CategoryReference {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedOnReference {
    
    private string refField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public enum PolicyClass {
    
    /// <remarks/>
    User,
    
    /// <remarks/>
    Machine,
    
    /// <remarks/>
    Both,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class PolicyList {
    
    private PolicyDefinition[] policyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("policy")]
    public PolicyDefinition[] policy {
        get {
            return this.policyField;
        }
        set {
            this.policyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class Category {
    
    private Annotation[] annotationField;
    
    private CategoryReference parentCategoryField;
    
    private string[] seeAlsoField;
    
    private string keywordsField;
    
    private string nameField;
    
    private string displayNameField;
    
    private string explainTextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation")]
    public Annotation[] annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public CategoryReference parentCategory {
        get {
            return this.parentCategoryField;
        }
        set {
            this.parentCategoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("seeAlso")]
    public string[] seeAlso {
        get {
            return this.seeAlsoField;
        }
        set {
            this.seeAlsoField = value;
        }
    }
    
    /// <remarks/>
    public string keywords {
        get {
            return this.keywordsField;
        }
        set {
            this.keywordsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string explainText {
        get {
            return this.explainTextField;
        }
        set {
            this.explainTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class CategoryList {
    
    private Category[] categoryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public Category[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedAndCondition {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("range", typeof(SupportedOnRange))]
    [System.Xml.Serialization.XmlElementAttribute("reference", typeof(SupportedOnReference))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedOnRange {
    
    private string refField;
    
    private uint minVersionIndexField;
    
    private bool minVersionIndexFieldSpecified;
    
    private uint maxVersionIndexField;
    
    private bool maxVersionIndexFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint minVersionIndex {
        get {
            return this.minVersionIndexField;
        }
        set {
            this.minVersionIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool minVersionIndexSpecified {
        get {
            return this.minVersionIndexFieldSpecified;
        }
        set {
            this.minVersionIndexFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint maxVersionIndex {
        get {
            return this.maxVersionIndexField;
        }
        set {
            this.maxVersionIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool maxVersionIndexSpecified {
        get {
            return this.maxVersionIndexFieldSpecified;
        }
        set {
            this.maxVersionIndexFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedOrCondition {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("range", typeof(SupportedOnRange))]
    [System.Xml.Serialization.XmlElementAttribute("reference", typeof(SupportedOnReference))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedOnDefinition {
    
    private object itemField;
    
    private string nameField;
    
    private string displayNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("and", typeof(SupportedAndCondition))]
    [System.Xml.Serialization.XmlElementAttribute("or", typeof(SupportedOrCondition))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedMinorVersion {
    
    private string displayNameField;
    
    private string nameField;
    
    private uint versionIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint versionIndex {
        get {
            return this.versionIndexField;
        }
        set {
            this.versionIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedMajorVersion {
    
    private SupportedMinorVersion[] minorVersionField;
    
    private string nameField;
    
    private string displayNameField;
    
    private uint versionIndexField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("minorVersion")]
    public SupportedMinorVersion[] minorVersion {
        get {
            return this.minorVersionField;
        }
        set {
            this.minorVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint versionIndex {
        get {
            return this.versionIndexField;
        }
        set {
            this.versionIndexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedProduct {
    
    private SupportedMajorVersion[] majorVersionField;
    
    private string nameField;
    
    private string displayNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("majorVersion")]
    public SupportedMajorVersion[] majorVersion {
        get {
            return this.majorVersionField;
        }
        set {
            this.majorVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class SupportedOnTable {
    
    private SupportedProduct[] productsField;
    
    private SupportedOnDefinition[] definitionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("product", IsNullable=false)]
    public SupportedProduct[] products {
        get {
            return this.productsField;
        }
        set {
            this.productsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("definition", IsNullable=false)]
    public SupportedOnDefinition[] definitions {
        get {
            return this.definitionsField;
        }
        set {
            this.definitionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class LocalizationResourceReference {
    
    private string minRequiredRevisionField;
    
    private string fallbackCultureField;
    
    public LocalizationResourceReference() {
        this.fallbackCultureField = "en-US";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string minRequiredRevision {
        get {
            return this.minRequiredRevisionField;
        }
        set {
            this.minRequiredRevisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
    [System.ComponentModel.DefaultValueAttribute("en-US")]
    public string fallbackCulture {
        get {
            return this.fallbackCultureField;
        }
        set {
            this.fallbackCultureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
public partial class FileReference {
    
    private string fileNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3062.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions")]
[System.Xml.Serialization.XmlRootAttribute("policyDefinitionResources", Namespace="http://www.microsoft.com/GroupPolicy/PolicyDefinitions", IsNullable=false)]
public partial class PolicyDefinitionResources {
    
    private string displayNameField;
    
    private string descriptionField;
    
    private Annotation[] annotationField;
    
    private Localization resourcesField;
    
    private string revisionField;
    
    private string schemaVersionField;
    
    /// <remarks/>
    public string displayName {
        get {
            return this.displayNameField;
        }
        set {
            this.displayNameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("annotation")]
    public Annotation[] annotation {
        get {
            return this.annotationField;
        }
        set {
            this.annotationField = value;
        }
    }
    
    /// <remarks/>
    public Localization resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string schemaVersion {
        get {
            return this.schemaVersionField;
        }
        set {
            this.schemaVersionField = value;
        }
    }
}
